name: CI CD Django

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: facecris_db
          MYSQL_ROOT_PASSWORD: M1P@ssw0rd!Str0ng2024
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          path: facecris_blog 

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd facecris_blog
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for MySQL to start
        run: |
          until nc -z -v -w30 127.0.0.1 3306
          do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Run migrations
        env:
          MYSQL_DATABASE: facecris_db
          MYSQL_USER: root
          MYSQL_PASSWORD: M1P@ssw0rd!Str0ng2024
          MYSQL_HOST: 127.0.0.1
        run: |
          cd facecris_blog
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        env:
          MYSQL_DATABASE: facecris_db
          MYSQL_USER: root
          MYSQL_PASSWORD: M1P@ssw0rd!Str0ng2024
          MYSQL_HOST: 127.0.0.1
        run: |
          cd facecris_blog
          source venv/bin/activate
          python manage.py test

      - name: Deploy to Server
        env:
           SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no frandjans@193.203.167.54 "
          if [ -d /home/frandjans/facecris_blog/.git ]; then 
              cd /home/frandjans/actions-runner/_work/facecris_blog git fetch --all && git reset --hard origin/main; 
          else 
              git clone git@github.com:ServiGram/facecris_blog.git /home/frandjans/actions-runner/_work; 
          fi"
          rm /tmp/deploy_key
        

