name: CI CD Django

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11]  # Usa versiones compatibles con Django 5.1.2

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for MySQL to start
        run: |
          until nc -z -v -w30 127.0.0.1 3306
          do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Run migrations
        env:
          MYSQL_DATABASE: facecris_db
          MYSQL_USER: root
          MYSQL_PASSWORD: M1P@ssw0rd!Str0ng2024
          MYSQL_HOST: 127.0.0.1
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        env:
          MYSQL_DATABASE: facecris_db
          MYSQL_USER: root
          MYSQL_PASSWORD: M1P@ssw0rd!Str0ng2024
          MYSQL_HOST: 127.0.0.1
        run: |
          source venv/bin/activate
          python manage.py test

