name: CI CD Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          path: facecris_blog 

      - name: Deploy to Server
        env:
           SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no frandjans@193.203.167.54 "
          cd ~/facecris_blog || git clone git@github.com:ServiGram/facecris_blog.git ~/facecris_blog;
          cd ~/facecris_blog && git pull origin main;
          sudo docker-compose down;
          sudo docker-compose up --build -d;
          "
          rm /tmp/deploy_key
